### ISSUE TITLE
Fully convolutional AutoEncoder

### ISSUE THREAD

**Issue by dawrym** [justinshenk/delve#4]
Hello, 

I have developed AutoEncoder which is fully convolutional and I wanted to check what is the utilization of convolutional layers in it (no dense), but I am not able to do it with this module. Even though, it is written that conv layers are supported.

**Comment by justinshenk** [comment]
Please see `example_deep.py` for an example of how to use it with
convolutional layers. Let me know if you have any questions.

**Comment by dawrym** [comment]
```
encoder:   0%|                                          | 0/100 [00:00<?, ?it/s]

decoder:   0%|                                          | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "...autoencoder.py", line 384, in <module>
    pipeline.fit()
  File "...autoencoder.py", line 112, in fit
    img, output = self.train_model(criterion, idx, optimizer, sample, writer)
  File "...autoencoder.py", line 158, in train_model
    output = self.model(img)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "...autoencoder.py", line 235, in forward
    x = self.encoder(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    hook_result = hook(self, input, result)
  File "/opt/conda/lib/python3.6/site-packages/delve-0.1.5-py3.6.egg/delve/main.py", line 233, in record_layer_saturation
    if layer.forward_iter % layer.interval == 0:
TypeError: unsupported operand type(s) for %: 'int' and 'str'
```

So I've got something like this

**Comment by justinshenk** [comment]
Somehow `log_interval` in `CheckLayerSat` is receiving a string. Yours should look something like:

```python
stats = CheckLayerSat(logging_dir='logging_dir', modules=net)
```

Can you share the command you are using, the version of delve and torch?

**Comment by justinshenk** [comment]
Closing stale issue.
