### ISSUE TITLE
Installation issue with readme file

### ISSUE THREAD

**Issue by Garrus990** [justinshenk/delve#6]
Hi,

I am trying to install delve through `pip install delve` (pip v. 18.1 on python 3.6.6) and there appears to be an error regarding README.md file:

There appears this error:
```
Collecting delve
  Downloading https://files.pythonhosted.org/packages/13/06/70419c15e345c869fea16f9a730009c220501d2ab93891fb7157d56008fb/delve-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2f5mmvyc/delve/setup.py", line 24, in <module>
        long_description=open("README.md").read(),
      File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1587: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2f5mmvyc/delve/
```

I believe it is related to the animations you put into the readme which are treated as binary records, not acceptable by `read()` function.

**Comment by justinshenk** [comment]
Thanks for pointing out the error you found. I think I fixed it in version
delve==0.1.7. Please try installing it again and let me know if you have
any further issues.
