### ISSUE TITLE
Does it work with submodules?

### ISSUE THREAD

**Issue by stared** [justinshenk/delve#7]
Typically I use modules within `nn.Sequential` or custom-defined modules.

```python
class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        super(TwoLayerNet, self).__init__()
        self.fc = torch.nn.Sequential(
            torch.nn.Linear(D_in, H),
            torch.nn.Linear(H, D_out)
        )

    def forward(self, x):
        return self.fc(x)
```

and then `layers = model.parameters()`. However, I get an error:

```
Traceback (most recent call last):
  File "example_submodule.py", line 43, in <module>
    stats = CheckLayerSat('regression/h{}'.format(h), layers)
  File "/Users/pmigdal/not_my_repos/delve/delve/main.py", line 50, in __init__
    self.layers = self._get_layers(modules)
  File "/Users/pmigdal/not_my_repos/delve/delve/main.py", line 167, in _get_layers
    for name in modules.state_dict().keys():
AttributeError: 'generator' object has no attribute 'state_dict'
```

(for full code example, see: https://gist.github.com/stared/b598c03ade397baf3fa03c52bd79e90d)

Does it work with submodules?

**Comment by stared** [comment]
@justinshenk Awesome! And I am impressed by your pace. :)
